image:
  file: .gitpod.Dockerfile

ports:
  - port: 9000-9100
    onOpen: ignore
  - port: 1024
    onOpen: ignore

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - ms-dotnettools.vscode-dotnet-runtime
    - muhammad-sammy.csharp
    #- ms-dotnettools.csharp
    #- ms-dotnettools.dotnet-interactive-vscode



