image:
  file: .gitpod.Dockerfile

ports:
  - port: 9000-9100
    onOpen: ignore
  - port: 1024-1064
    onOpen: ignore

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - ms-dotnettools.vscode-dotnet-runtime
    - muhammad-sammy.csharp
    # Extensions below are not in OpenVSX repository (can they still be used here?)
    - ms-dotnettools.csharp
    - ms-dotnettools.dotnet-interactive-vscode

tasks:
  - name: terminal
    command: bash
    openMode: split-right
  - name: code
    command: open fizzbuzz.ipynb
    openMode: split-left
